name: student_mgmt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  google_fonts: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

<<<<<<< HEAD
  assets:
    - assets/images/student-icon.png
    - assets/images/emergency-people-icon.png
    - assets/images/medication-icon.png
    - assets/images/activites-icon.png
    - assets/images/time-table-icon.png
    - assets/images/fees-icon.png
    - assets/images/child-feedback-icon.png
    - assets/images/time-table-icon.png
    - assets/images/tasks-icon.png
    - assets/images/class-icon.png
    - assets/images/complaint-icon.png
    - assets/images/logout-icon.png
    - assets/images/teacher-icon.png
=======
assets:
   - assets/images/student-icon.png
   - assets/images/emergency-people-icon.png
   - assets/images/medication-icon.png
   - assets/images/activites-icon.png
   - assets/images/time-table-icon.png
   - assets/images/fees-icon.png
   - assets/images/child-feedback-icon.png
   - assets/images/time-table-icon.png
   - assets/images/tasks-icon.png
   - assets/images/class-icon.png
   - assets/images/complaint-icon.png
   - assets/images/logout-icon.png
>>>>>>> 158f07772430768aae0e51e1dc89cc52c912a87b

